version: "3"

services:
  postgres:
    image: matthieuberger/postgres-multi-db:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=platform

  temporal:
    restart: on-failure:3 
    build:
      context: ./temporal
      dockerfile: Dockerfile
    ports:
      - 7233:7233
      - 8233:8233
    volumes:
      - ./tmp/teamporal:/usr/temporal/

  api:
    container_name: uzielvaldez-platform-api
    build:
      context: ./platform-api
      dockerfile: Dockerfile
    volumes:
      - ./platform-api:/usr/app
    depends_on:
      - postgres
    restart: on-failure:3
    ports:
      - 3000:3000
  # Email worker service
  # email-worker:...

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./webapp:/usr/webapp:cached
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

networks:
  default:
    driver: bridge
    name: mentium-net
