name: Unit Testing
on: [pull_request] 

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./platform-api
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn run lint
      - name: Run tests
        run: yarn run test
